name: Pull Request
run-name: "PR: ${{ github.event.pull_request.title || 'Manual Trigger' }}"

permissions:
  contents: read
on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  AGENT_SRC_PATH: "SRC/Agent"
  SW_OUT_PATH: "SW_OUT"
  PR_BRANCH: ${{ github.event.pull_request.title }}

jobs:
  build-agent:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore "/OurDLP.slnx"

      - name: Build Agent
        run: ./scripts/build.bat

      - name: Set Artifact name
        run: echo "TODAY=$(Get-Date -Format 'yyMMdd')" >> $env:GITHUB_ENV

      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OURDLP_PULL_REQUEST_${{ env.TODAY }}
          path: ${{ env.SW_OUT_PATH }}
          retention-days: 7
