name: Release

on:
  workflow_dispatch:
    inputs:
      TEST_RELEASE:
        type: choice
        options:
          - YES
          - NO
        description: "Choose yes for testing"
        required: true
        default: YES
      TAG:
        description: "Tag for release"
        required: true
        default: "v1.0.0"

env:
  AGENT_SRC_PATH: "SRC/agent"
  SW_OUT_PATH: "SW_OUT"

permissions:
  contents: write

jobs:
  build-agent:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore "$env:AGENT_SRC_PATH/agent.slnx"

      - name: Build Agent
        run: |
          dotnet publish "$env:AGENT_SRC_PATH/agent.csproj" `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishAot=true `
            -o "$env:SW_OUT_PATH"

      - name: Set Artifact name
        run: echo "TODAY=$(Get-Date -Format 'yyMMdd')" >> $env:GITHUB_ENV

      - name: Archive Artifact
        if: ${{ github.event.inputs.TEMP_RELEASE.options == 'YES'}}
        uses: actions/upload-artifact@v4
        with:
          name: OURDLP_TEST_RELEASE_${{ env.TODAY }}
          path: ${{ env.SW_OUT_PATH }}
          retention-days: 7

      - name: Zip Artifact
        if: ${{ github.event.inputs.TEMP_RELEASE.options == 'NO'}}
        run: Compress-Archive -Path "${{ env.SW_OUT_PATH }}/*" -DestinationPath "${{ env.SW_OUT_PATH }}/OURDLP_REALEASE_${{ github.event.inputs.TAG }}_${{ env.TODAY }}.zip"

      - name: GitHub Release
        if: ${{ github.event.inputs.TEMP_RELEASE.options == 'YES'}}
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ env.SW_OUT_PATH }}/OURDLP_REALEASE_${{ github.event.inputs.TAG }}_${{ env.TODAY }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
