name: Release

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: "BRANCH (Input branch to build)"
        required: true
        default: "main"
      TEST_RELEASE:
        type: choice
        options:
          - "YES"
          - "NO"
        description: "TEST_RELEASE (Choose YES for test, NO for release) "
        required: true
        default: "YES"
      TAG:
        description: "TAG (Input Tag for release)"
        required: true
        default: "v1.0.0"

env:
  AGENT_SRC_PATH: "SRC/agent"
  SW_OUT_PATH: "SW_OUT"
  RELEASE_TAG: "${{ github.event.inputs.TAG }}"
  RELEASE_BRANCH: ${{ github.event.inputs.BRANCH }}

permissions:
  contents: write

jobs:
  build-agent:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env:RELEASE_BRANCH}}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore "$env:AGENT_SRC_PATH/agent.slnx"

      - name: Build Agent
        run: |
          dotnet publish "$env:AGENT_SRC_PATH/agent.csproj" `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishAot=true `
            -o "$env:SW_OUT_PATH"

      - name: Set Artifact name
        run: echo "TODAY=$(Get-Date -Format 'yyMMdd')" >> $env:GITHUB_ENV

      - name: Archive Artifact
        if: ${{ github.event.inputs.TEST_RELEASE == 'YES' }}
        uses: actions/upload-artifact@v4
        with:
          name: OURDLP_TEST_RELEASE_${{ env.TODAY }}
          path: ${{ env.SW_OUT_PATH }}
          retention-days: 7

      - name: Zip Artifact
        if: ${{ github.event.inputs.TEST_RELEASE == 'NO' }}
        run: Compress-Archive -Path "${{ env.SW_OUT_PATH }}/*" -DestinationPath "./OURDLP_RELEASE_${{ env.RELEASE_TAG }}_${{ env.TODAY }}.zip"

      - name: GitHub Release
        if: ${{ github.event.inputs.TEST_RELEASE == 'NO' }}
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_TAG }}
          body: "Build from branch ${{ github.event.inputs.BRANCH }}"
          files: "./OURDLP_RELEASE_${{ env.RELEASE_TAG }}_${{ env.TODAY }}.zip"
          tag_name: ${{ github.event.inputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
